### ISSUE TITLE
Падение на EDT 2020.5+

### ISSUE THREAD

**Issue by DitriXNew** [yukon39/coverage-cli#26]
Писал в другую репу - сказали не их проблема.
https://github.com/proDOOMman/Coverage41C/issues/58

C:\Users\DitriX>coverage-cli start --infobase test_database --output coverage.csv
?????????? - ?????? pid-????: C:\Users\DitriX\AppData\Local\Temp\coverage.17820.pid

C:\Users\DitriX>SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/C:/EDT/components/1c-edt-2020.5.1+23-x86_64/plugins/ch.qos.logback.slf4j_1.1.2.v20160301-0943.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/C:/EDT/components/1c-edt-2020.5.1+23-x86_64/plugins/org.slf4j.impl.log4j12_1.7.2.v20131105-2200.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
14:19:07.588 [main] DEBUG org.eclipse.jetty.util.log - Logging to Logger[org.eclipse.jetty.util.log] via org.eclipse.jetty.util.log.Slf4jLog
14:19:07.618 [main] INFO  org.eclipse.jetty.util.log - Logging initialized @1881ms to org.eclipse.jetty.util.log.Slf4jLog
14:19:07.706 [main] DEBUG o.e.j.u.component.AbstractLifeCycle - starting org.eclipse.jetty.client.HttpClient@7fc44dec
SLF4J: Failed toString() invocation on an object of type [org.eclipse.jetty.util.component.ContainerLifeCycle$Bean]
java.lang.IncompatibleClassChangeError: org.eclipse.jetty.util.ssl.SslContextFactory and org.eclipse.jetty.util.ssl.SslContextFactory$Client disagree on InnerClasses attribute
        at java.base/java.lang.Class.getDeclaringClass0(Native Method)
        at java.base/java.lang.Class.isTopLevelClass(Class.java:1693)
        at java.base/java.lang.Class.getSimpleBinaryName(Class.java:1678)
        at java.base/java.lang.Class.getSimpleName0(Class.java:1562)
        at java.base/java.lang.Class.getSimpleName(Class.java:1553)
        at org.eclipse.jetty.util.ssl.SslContextFactory.toString(SslContextFactory.java:1770)
        at java.base/java.util.Formatter$FormatSpecifier.printString(Formatter.java:3031)
        at java.base/java.util.Formatter$FormatSpecifier.print(Formatter.java:2908)
        at java.base/java.util.Formatter.format(Formatter.java:2673)
        at java.base/java.util.Formatter.format(Formatter.java:2609)
        at java.base/java.lang.String.format(String.java:2897)
        at org.eclipse.jetty.util.component.ContainerLifeCycle$Bean.toString(ContainerLifeCycle.java:796)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:305)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:277)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:231)
        at org.eclipse.jetty.util.log.JettyAwareLogger.log(JettyAwareLogger.java:680)
        at org.eclipse.jetty.util.log.JettyAwareLogger.debug(JettyAwareLogger.java:224)
        at org.eclipse.jetty.util.log.Slf4jLog.debug(Slf4jLog.java:97)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:347)
        at org.eclipse.jetty.util.component.ContainerLifeCycle.addBean(ContainerLifeCycle.java:250)
        at org.eclipse.jetty.client.HttpClient.doStart(HttpClient.java:203)
        at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
        at com._1c.g5.v8.dt.internal.debug.core.runtime.client.RuntimeDebugHttpClient.<init>(RuntimeDebugHttpClient.java:165)
        at com.clouds42.Coverage41C.call(Coverage41C.java:84)
        at com.clouds42.Coverage41C.call(Coverage41C.java:34)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1783)
        at picocli.CommandLine.access$900(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2150)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2144)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2108)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:1975)
        at picocli.CommandLine.execute(CommandLine.java:1904)
        at com.clouds42.Coverage41C.main(Coverage41C.java:62)
14:19:07.741 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.client.HttpClient@7fc44dec added [FAILED toString()]
14:19:07.770 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.client.HttpClient@7fc44dec added {QueuedThreadPool[HttpClient@7fc44dec]@64df9a61{STOPPED,8<=0<=200,i=0,q=0}[org.eclipse.jetty.util.thread.TryExecutor$$Lambda$67/0x0000000800177c40@1ddae9b5],AUTO}
14:19:07.774 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.client.HttpClient@7fc44dec added {org.eclipse.jetty.io.MappedByteBufferPool@3383649e,POJO}
14:19:07.782 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.client.HttpClient@7fc44dec added {org.eclipse.jetty.util.thread.ScheduledExecutorScheduler@74e47444,AUTO}
14:19:07.783 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.client.HttpClient@7fc44dec added {org.eclipse.jetty.client.http.HttpClientTransportOverHTTP@9bd0fa6,AUTO}
14:19:07.786 [main] DEBUG o.e.j.u.component.ContainerLifeCycle - org.eclipse.jetty.client.HttpClient@7fc44dec added {org.eclipse.jetty.util.SocketAddressResolver$Async@46f699d5,POJO}

**Comment by DitriXNew** [comment]
На последнем релизе проблема ушла
